#!/bin/bash

echo "====================================================="
echo "  This installer is deprecated and no longer supported"
echo "====================================================="
echo ""
echo "Please use the new Python installer instead:"
echo ""
echo "  python install.py"
echo ""
echo "The new installer handles:"
echo "  - Automatic Python environment detection"
echo "  - Version validation (diffusers >= 0.33.0)"
echo "  - nvdiffrast installation with fallbacks"
echo "  - Post-install verification"
echo ""
echo "For Windows-specific issues, see TROUBLESHOOTING-WINDOWS.md"
echo "====================================================="
echo ""
read -p "Press any key to continue..."